In [ ]:
import numpy as np
import pandas as pd

### Loading Data

In [2]:
train = pd.read_csv('../Data/train.csv')
test = pd.read_csv('../Data/test.csv')

In [3]:
train.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [4]:
test.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population
0,577347,120.719779,23.924249,23.668066,21.951680,21.086183,20.180032,19.202124,0.429042,G/K,Red_Sequence
1,577348,219.414419,42.171651,24.902933,22.338822,20.732163,19.860330,19.687691,0.867305,M,Red_Sequence
2,577349,173.568731,-1.756400,19.427591,18.474633,17.551314,16.570674,16.176765,0.224234,G/K,Blue_Cloud
3,577350,184.903993,-1.411074,23.121029,21.526855,20.670159,20.417633,20.699095,0.066507,G/K,Red_Sequence
4,577351,222.487816,15.381403,25.094282,22.643981,21.123173,19.439500,19.094158,0.977218,M,Red_Sequence

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 577347 entries, 0 to 577346
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 577347 non-null  int64
 1   alpha              577347 non-null  float64
 2   delta              577347 non-null  float64
 3   u                  577347 non-null  float64
 4   g                  577347 non-null  float64
 5   r                  577347 non-null  float64
 6   i                  577347 non-null  float64
 7   z                  577347 non-null  float64
 8   redshift           577347 non-null  float64
 9   spectral_type      577347 non-null  str
 10  galaxy_population  577347 non-null  str
 11  class              577347 non-null  str
dtypes: float64(8), int64(1), str(3)
memory usage: 62.9 MB

In [6]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 247435 entries, 0 to 247434
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 247435 non-null  int64
 1   alpha              247435 non-null  float64
 2   delta              247435 non-null  float64
 3   u                  247435 non-null  float64
 4   g                  247435 non-null  float64
 5   r                  247435 non-null  float64
 6   i                  247435 non-null  float64
 7   z                  247435 non-null  float64
 8   redshift           247435 non-null  float64
 9   spectral_type      247435 non-null  str
 10  galaxy_population  247435 non-null  str
dtypes: float64(8), int64(1), str(2)
memory usage: 23.8 MB

### Data preprocessing

In [7]:
train.isna().sum()

id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
class                0
dtype: int64

In [8]:
test.isna().sum()

id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
dtype: int64

In [9]:
train.duplicated().sum()

np.int64(0)

In [10]:
train.select_dtypes(include = 'number').columns

Index(['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift'], dtype='str')

In [11]:
train.select_dtypes(include = 'object').columns

/tmp/ipykernel_57720/377346685.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train.select_dtypes(include = 'object').columns

Index(['spectral_type', 'galaxy_population', 'class'], dtype='str')

In [12]:
test.select_dtypes(include = 'number').columns

Index(['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift'], dtype='str')

In [13]:
test.select_dtypes(include = 'object').columns

/tmp/ipykernel_57720/642666790.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  test.select_dtypes(include = 'object').columns

Index(['spectral_type', 'galaxy_population'], dtype='str')

### Dropping unnecessary columns

In [14]:
train.drop(columns = ['id'], inplace = True)

In [15]:
test_ids = test['id']
test.drop(columns = ['id'], inplace = True)

### Splitting data

In [16]:
X = train.drop(columns = ['class'])
y = train['class']

In [17]:
num_cols = X.select_dtypes(include = 'number').columns.tolist()
cat_cols = X.select_dtypes(include = 'object').columns.tolist()

/tmp/ipykernel_57720/3956851967.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include = 'object').columns.tolist()

In [18]:
cat_cols

['spectral_type', 'galaxy_population']

In [19]:
for i in cat_cols:
    print(f'{i} Unique Values: {train[i].unique()}')

spectral_type Unique Values: <ArrowStringArray>
['M', 'O/B', 'G/K', 'A/F']
Length: 4, dtype: str
galaxy_population Unique Values: <ArrowStringArray>
['Red_Sequence', 'Blue_Cloud']
Length: 2, dtype: str

In [20]:
# we need to split the cat_cols further more 
ohe_cols = [cat_cols[0]]
ord_cols = [cat_cols[1]]

### Creating Pipeline

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, OrdinalEncoder

In [24]:
num_pipe = Pipeline(steps = [
    ('Scaling', StandardScaler())
])

ohe_pipe = Pipeline(steps = [
    ('OneHotEncoder', OneHotEncoder())
])

ord_pipe = Pipeline(steps = [
    ('OrdinalEncoder', OrdinalEncoder())
])

In [25]:
preprocessor = ColumnTransformer(transformers = [
    ('numerical transformation', num_pipe, num_cols),
    ('one hot transformation', ohe_pipe, ohe_cols),
    ('ordinal transformation', ord_pipe, ord_cols)
])

In [26]:
X_transformed = preprocessor.fit_transform(X)
test_transformed = preprocessor.transform(test)

### Training

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score, recall_score, balanced_accuracy_score

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size = 0.2, random_state = 42)

In [31]:
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

In [32]:
models = {
    'LogisticRegression': LogisticRegression(),
    'RandomForestClassifier': RandomForestClassifier(),
    'XGBClassifier': XGBClassifier(),
    'CatboostClassifier': CatBoostClassifier(verbose = False)
}

In [33]:
best_model = None
best_score = 0
model_name = ''

for name, model in models.items():
    print('Model name: ', name)
    model.fit(X_train, y_train_enc)
    y_pred = model.predict(X_test)
    print('Metrics for', name)
    print('F1 score: ', f1_score(y_test_enc, y_pred, average = 'macro'))
    print('Recall score: ', recall_score(y_test_enc, y_pred, average = 'macro'))
    print('Balanced accuracy score: ', balanced_accuracy_score(y_test_enc, y_pred))
    print('*' * 100)

    score = balanced_accuracy_score(y_test_enc, y_pred)
    if score > best_score:
        best_score = score
        best_name = name
        best_model = model

    print(f'Best model: {name}, with balanced accuracy score: {best_score}')

Model name:  LogisticRegression
Metrics for LogisticRegression
F1 score:  0.8976808754913441
Recall score:  0.8948990672266047
Balanced accuracy score:  0.8948990672266047
****************************************************************************************************
Best model: LogisticRegression, with balanced accuracy score: 0.8948990672266047
Model name:  RandomForestClassifier
Metrics for RandomForestClassifier
F1 score:  0.9461910601318428
Recall score:  0.9448509132942134
Balanced accuracy score:  0.9448509132942134
****************************************************************************************************
Best model: RandomForestClassifier, with balanced accuracy score: 0.9448509132942134
Model name:  XGBClassifier
Metrics for XGBClassifier
F1 score:  0.9558878789959255
Recall score:  0.9556418311025242
Balanced accuracy score:  0.9556418311025242
****************************************************************************************************
Best model: XGBClassifier, with balanced accuracy score: 0.9556418311025242
Model name:  CatboostClassifier
Metrics for CatboostClassifier
F1 score:  0.9530817917483122
Recall score:  0.9521142806573134
Balanced accuracy score:  0.9521142806573134
****************************************************************************************************
Best model: CatboostClassifier, with balanced accuracy score: 0.9556418311025242

In [35]:
results = model.predict(test_transformed)

In [37]:
results = le.inverse_transform(results)

/home/kman/Projects/Stellar-Class/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:161: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [38]:
results

array(['GALAXY', 'GALAXY', 'GALAXY', ..., 'GALAXY', 'QSO', 'GALAXY'],
      shape=(247435,), dtype=object)

### Saving Result

In [41]:
subbmission = pd.DataFrame({
    'id': test_ids,
    'class': results
    })

subbmission.to_csv('../Data/submission.csv', index = False)